<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddToCartButtons</name>
   <tag></tag>
   <elementGuidId>fe2a6acc-3c79-492c-8c45-76c2e1654a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@name, 'add-to-cart-')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-to-cart-</value>
      <webElementGuid>6799a422-4c42-4cfd-b17e-b3ca5215c267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d48d9c4-8a61-49c7-812b-d7f6154521cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
